# Generated by Django 3.1.1 on 2020-09-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('artist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'artists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Designers',
            fields=[
                ('designer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('designer', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'designers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Families',
            fields=[
                ('family_id', models.IntegerField(primary_key=True, serialize=False)),
                ('family', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'families',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameArtists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'game_artists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'game_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameDesigners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'game_designers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameFamilies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'game_families',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameMechanics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'game_mechanics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GamePublishers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'game_publishers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('average', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('minplayers', models.IntegerField(blank=True, null=True)),
                ('maxplayers', models.IntegerField(blank=True, null=True)),
                ('playingtime', models.IntegerField(blank=True, null=True)),
                ('yearpublished', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=100, null=True)),
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'games',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameSubdomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'game_subdomains',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mechanics',
            fields=[
                ('mechanic_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mechanic', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'mechanics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('publisher_id', models.IntegerField(primary_key=True, serialize=False)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'publishers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subdomains',
            fields=[
                ('subdomain_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subdomain', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'subdomains',
                'managed': False,
            },
        ),
    ]
