# Generated by Django 3.1.1 on 2020-09-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'artists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('designer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('designer', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'designers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('family_id', models.IntegerField(primary_key=True, serialize=False)),
                ('family', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'families',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('average', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('minplayers', models.IntegerField(blank=True, null=True)),
                ('maxplayers', models.IntegerField(blank=True, null=True)),
                ('playingtime', models.IntegerField(blank=True, null=True)),
                ('yearpublished', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=100, null=True)),
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'games',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'game_artists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'game_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameDesigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'game_designers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'game_families',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameMechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'game_mechanics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GamePublisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'game_publishers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameSubdomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'game_subdomains',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('mechanic_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mechanic', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'mechanics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.IntegerField(primary_key=True, serialize=False)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'publishers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('subdomain_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subdomain', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'subdomains',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Artists',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Designers',
        ),
        migrations.DeleteModel(
            name='Families',
        ),
        migrations.DeleteModel(
            name='GameArtists',
        ),
        migrations.DeleteModel(
            name='GameCategories',
        ),
        migrations.DeleteModel(
            name='GameDesigners',
        ),
        migrations.DeleteModel(
            name='GameFamilies',
        ),
        migrations.DeleteModel(
            name='GameMechanics',
        ),
        migrations.DeleteModel(
            name='GamePublishers',
        ),
        migrations.DeleteModel(
            name='Games',
        ),
        migrations.DeleteModel(
            name='GameSubdomains',
        ),
        migrations.DeleteModel(
            name='Mechanics',
        ),
        migrations.DeleteModel(
            name='Publishers',
        ),
        migrations.DeleteModel(
            name='Subdomains',
        ),
    ]
