# Generated by Django 3.1.1 on 2020-09-11 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0003_auto_20200910_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artists',
            options={'managed': False, 'verbose_name': 'Artist', 'verbose_name_plural': 'Artists'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'managed': False, 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='designers',
            options={'managed': False, 'verbose_name': 'Designer', 'verbose_name_plural': 'Designers'},
        ),
        migrations.AlterModelOptions(
            name='families',
            options={'managed': False, 'verbose_name': 'Family', 'verbose_name_plural': 'Families'},
        ),
        migrations.AlterModelOptions(
            name='gameartists',
            options={'managed': False, 'verbose_name': 'Game Artist', 'verbose_name_plural': 'Game Artists'},
        ),
        migrations.AlterModelOptions(
            name='gamecategories',
            options={'managed': False, 'verbose_name': 'Game Category', 'verbose_name_plural': 'Game Categories'},
        ),
        migrations.AlterModelOptions(
            name='gamedesigners',
            options={'managed': False, 'verbose_name': 'Game Designer', 'verbose_name_plural': 'Game Designers'},
        ),
        migrations.AlterModelOptions(
            name='gamefamilies',
            options={'managed': False, 'verbose_name': 'Game Family', 'verbose_name_plural': 'Game Families'},
        ),
        migrations.AlterModelOptions(
            name='gamemechanics',
            options={'managed': False, 'verbose_name': 'Game Mechanic', 'verbose_name_plural': 'Game Mechanics'},
        ),
        migrations.AlterModelOptions(
            name='gamepublishers',
            options={'managed': False, 'verbose_name': 'Game Publisher', 'verbose_name_plural': 'Game Publishers'},
        ),
        migrations.AlterModelOptions(
            name='games',
            options={'managed': False, 'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AlterModelOptions(
            name='gamesubdomains',
            options={'managed': False, 'verbose_name': 'Game Subdomain', 'verbose_name_plural': 'Game Subdomains'},
        ),
        migrations.AlterModelOptions(
            name='mechanics',
            options={'managed': False, 'verbose_name': 'Mechanic', 'verbose_name_plural': 'Mechanics'},
        ),
        migrations.AlterModelOptions(
            name='publishers',
            options={'managed': False, 'verbose_name': 'Publisher', 'verbose_name_plural': 'Publishers'},
        ),
        migrations.AlterModelOptions(
            name='subdomains',
            options={'managed': False, 'verbose_name': 'Subdomain', 'verbose_name_plural': 'Subdomains'},
        ),
    ]
