# Generated by Django 3.1.1 on 2020-09-18 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0004_auto_20200910_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'managed': False, 'ordering': ['game_id'], 'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
    ]
